M48
; DRILL file {KiCad 7.0.8} date Thu 16 Nov 2023 03:54:06 PM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-16T15:54:06-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X160.897Y-80.884
X165.747Y-80.884
T2
X160.597Y-77.854
X166.047Y-77.854
T0
M30
